#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : grpcio-reflection
Version  : 1.42.0
Release  : 14
URL      : https://files.pythonhosted.org/packages/b7/ee/afc17aaf1980de8a7c81c3e35e09cc10aac21dc8f78b77fe8f820dffd080/grpcio-reflection-1.42.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/b7/ee/afc17aaf1980de8a7c81c3e35e09cc10aac21dc8f78b77fe8f820dffd080/grpcio-reflection-1.42.0.tar.gz
Summary  : Standard Protobuf Reflection Service for gRPC
Group    : Development/Tools
License  : Apache-2.0
Requires: grpcio-reflection-python = %{version}-%{release}
Requires: grpcio-reflection-python3 = %{version}-%{release}
Requires: grpcio
Requires: protobuf
BuildRequires : buildreq-distutils3
BuildRequires : grpcio
BuildRequires : protobuf

%description
==============================
        
        Reference package for reflection in GRPC Python.
        
        Supported Python Versions
        -------------------------
        Python >= 3.6
        
        Dependencies
        ------------
        
        Depends on the `grpcio` package, available from PyPI via `pip install grpcio`.

%package python
Summary: python components for the grpcio-reflection package.
Group: Default
Requires: grpcio-reflection-python3 = %{version}-%{release}

%description python
python components for the grpcio-reflection package.


%package python3
Summary: python3 components for the grpcio-reflection package.
Group: Default
Requires: python3-core
Provides: pypi(grpcio_reflection)
Requires: pypi(grpcio)
Requires: pypi(protobuf)

%description python3
python3 components for the grpcio-reflection package.


%prep
%setup -q -n grpcio-reflection-1.42.0
cd %{_builddir}/grpcio-reflection-1.42.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637177936
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
